/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as HelpfulRouteImport } from './routes/helpful'
import { Route as ExaminerRouteImport } from './routes/examiner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadingIndexRouteImport } from './routes/reading.index'
import { Route as ListeningIndexRouteImport } from './routes/listening.index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as ReadingTestIdRouteImport } from './routes/reading.$testId'
import { Route as ListeningTestIdRouteImport } from './routes/listening.$testId'
import { Route as ExamsCodeRouteImport } from './routes/exams.$code'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpfulRoute = HelpfulRouteImport.update({
  id: '/helpful',
  path: '/helpful',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminerRoute = ExaminerRouteImport.update({
  id: '/examiner',
  path: '/examiner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingIndexRoute = ReadingIndexRouteImport.update({
  id: '/reading/',
  path: '/reading/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningIndexRoute = ListeningIndexRouteImport.update({
  id: '/listening/',
  path: '/listening/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingTestIdRoute = ReadingTestIdRouteImport.update({
  id: '/reading/$testId',
  path: '/reading/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningTestIdRoute = ListeningTestIdRouteImport.update({
  id: '/listening/$testId',
  path: '/listening/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsCodeRoute = ExamsCodeRouteImport.update({
  id: '/exams/$code',
  path: '/exams/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/examiner': typeof ExaminerRoute
  '/helpful': typeof HelpfulRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/speaking': typeof SpeakingRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/exams/$code': typeof ExamsCodeRoute
  '/listening/$testId': typeof ListeningTestIdRoute
  '/reading/$testId': typeof ReadingTestIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/listening/': typeof ListeningIndexRoute
  '/reading/': typeof ReadingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/examiner': typeof ExaminerRoute
  '/helpful': typeof HelpfulRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/speaking': typeof SpeakingRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/exams/$code': typeof ExamsCodeRoute
  '/listening/$testId': typeof ListeningTestIdRoute
  '/reading/$testId': typeof ReadingTestIdRoute
  '/exams': typeof ExamsIndexRoute
  '/listening': typeof ListeningIndexRoute
  '/reading': typeof ReadingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/examiner': typeof ExaminerRoute
  '/helpful': typeof HelpfulRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/speaking': typeof SpeakingRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/exams/$code': typeof ExamsCodeRoute
  '/listening/$testId': typeof ListeningTestIdRoute
  '/reading/$testId': typeof ReadingTestIdRoute
  '/exams/': typeof ExamsIndexRoute
  '/listening/': typeof ListeningIndexRoute
  '/reading/': typeof ReadingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/examiner'
    | '/helpful'
    | '/portfolio'
    | '/privacy'
    | '/speaking'
    | '/terms'
    | '/vocabulary'
    | '/writing'
    | '/courses/$courseId'
    | '/exams/$code'
    | '/listening/$testId'
    | '/reading/$testId'
    | '/exams/'
    | '/listening/'
    | '/reading/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/examiner'
    | '/helpful'
    | '/portfolio'
    | '/privacy'
    | '/speaking'
    | '/terms'
    | '/vocabulary'
    | '/writing'
    | '/courses/$courseId'
    | '/exams/$code'
    | '/listening/$testId'
    | '/reading/$testId'
    | '/exams'
    | '/listening'
    | '/reading'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/examiner'
    | '/helpful'
    | '/portfolio'
    | '/privacy'
    | '/speaking'
    | '/terms'
    | '/vocabulary'
    | '/writing'
    | '/courses/$courseId'
    | '/exams/$code'
    | '/listening/$testId'
    | '/reading/$testId'
    | '/exams/'
    | '/listening/'
    | '/reading/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ExaminerRoute: typeof ExaminerRoute
  HelpfulRoute: typeof HelpfulRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  SpeakingRoute: typeof SpeakingRoute
  TermsRoute: typeof TermsRoute
  VocabularyRoute: typeof VocabularyRoute
  WritingRoute: typeof WritingRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  ExamsCodeRoute: typeof ExamsCodeRoute
  ListeningTestIdRoute: typeof ListeningTestIdRoute
  ReadingTestIdRoute: typeof ReadingTestIdRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  ListeningIndexRoute: typeof ListeningIndexRoute
  ReadingIndexRoute: typeof ReadingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpful': {
      id: '/helpful'
      path: '/helpful'
      fullPath: '/helpful'
      preLoaderRoute: typeof HelpfulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examiner': {
      id: '/examiner'
      path: '/examiner'
      fullPath: '/examiner'
      preLoaderRoute: typeof ExaminerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/': {
      id: '/reading/'
      path: '/reading'
      fullPath: '/reading/'
      preLoaderRoute: typeof ReadingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening/': {
      id: '/listening/'
      path: '/listening'
      fullPath: '/listening/'
      preLoaderRoute: typeof ListeningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading/$testId': {
      id: '/reading/$testId'
      path: '/reading/$testId'
      fullPath: '/reading/$testId'
      preLoaderRoute: typeof ReadingTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening/$testId': {
      id: '/listening/$testId'
      path: '/listening/$testId'
      fullPath: '/listening/$testId'
      preLoaderRoute: typeof ListeningTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$code': {
      id: '/exams/$code'
      path: '/exams/$code'
      fullPath: '/exams/$code'
      preLoaderRoute: typeof ExamsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ExaminerRoute: ExaminerRoute,
  HelpfulRoute: HelpfulRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  SpeakingRoute: SpeakingRoute,
  TermsRoute: TermsRoute,
  VocabularyRoute: VocabularyRoute,
  WritingRoute: WritingRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  ExamsCodeRoute: ExamsCodeRoute,
  ListeningTestIdRoute: ListeningTestIdRoute,
  ReadingTestIdRoute: ReadingTestIdRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  ListeningIndexRoute: ListeningIndexRoute,
  ReadingIndexRoute: ReadingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
